homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 32.8156
  longitude: 34.9892
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  customize: !include customize.yaml

#  Show links to resources in log and frontend
#introduction:

zone:
  - name: Home
    latitude: 32.823260
    longitude: 34.973303
    radius: 100
  #  icon: mdi:account-multiple


device_tracker:
  - platform: ping
    interval_seconds: 30
    consider_home: 60
    hosts:
      roe_phone: 192.168.1.11
      malina_phone: 192.168.1.14

  - platform: owntracks

mqtt:
  discovery: true
  broker: m23.cloudmqtt.com
  port: 14564
  username: mbvtncuy
  password: XYM9oO9BmSf3


calendar:
  - platform: todoist
    token: 8df992bf65b8f76f8f5c0e9e9b847b6283dc7816

light:
  - platform: hyperion
    name: TV Led Strip
    host: 192.168.1.13
    effect_list: 'Police Lights Solid'

weather:
  - platform: yweather
    woeid: 1967449
    name: Weather


influxdb:
  host: 127.0.0.1
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: cpuspeed

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
